run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - typecheck
  disable:
    - exhaustive
    - wrapcheck

issues:
  exclude-rules:
    # Allow unchecked errors in test files for setup code.
    - path: _test\.go
      linters:
        - errcheck
    # filepath.Glob errors are non-critical.
    - text: "filepath.Glob"
      linters:
        - errcheck
